name: pubish page to date structure

on:
  repository_dispatch:
    types:
      - resource-published
  workflow_dispatch:
    inputs:
      aem-page-path:
        description: 'Path of individual page published.'
        required: true

jobs:
  run-node-script:
    runs-on: ubuntu-latest
    env:
      DA_TOKEN: ${{ secrets.DA_TOKEN }}
      HELIX_TOKEN: ${{ secrets.HELIX_TOKEN }}
      AEM_PAGE_PATH: ${{ github.event.client_payload.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: .github/actions
        run: npm install
      - name: Run publisher
        run: node .github/actions/publisher.js 